use_frameworks!

platform :ios, '10.0'

target 'Hasher_Example' do
  pod 'Hasher', :path => '../'

  target 'Hasher_Tests' do
    inherit! :search_paths
    
    pod 'Quick'
    pod 'Nimble'
  end
end
